### ISSUE TITLE
Encounter in a Strange Land

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#101]
i guess this is the error:
[Error]: buildin_delitem: failed to delete 1 items (AID=2000001 item_id=654
[Debug]: Source (NPC): Desk#tl01 at que_avan01 (18,38)

my player reported me a bug in this quest:
http://irowiki.org/wiki/Encounter_in_a_Strange_Land

**Comment by exneval** [comment]
There's no such item id 654 in ragnarok, please check again in your script..
for the quest bug, you need to give more details, such as, in what step the bug is found
