### ISSUE TITLE
sura skills winmill and cused circle

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#102]
[CC TEST.txt](https://github.com/idathena/trunk/files/358554/CC.TEST.txt)

source: iro

**Comment by ernestfegarido** [comment]
just rename that from cc test.rrf

**Comment by ernestfegarido** [comment]
i also check rathena their cused circle is fixed

**Comment by exneval** [comment]
Halo, can you more describe what is wrong in idAthena, what is correct in iRO, thanks
