### ISSUE TITLE
Flash Combo

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#114]
i want to know if this skill gives certain additional attack

source: http://www.divine-pride.net/database/skill/5009/flash-combo

after i tried this skill i didn't get any bonus attack for 4 sec

i used level 1 to level 5 but nothing happens no additional attack

**Comment by exneval** [comment]
the additional attack already applied to the flash combo skills

**Comment by exneval** [comment]
You should compare flash combo skills with the normal one, the +200Atk already added in the output of skill
