### ISSUE TITLE
rA scripts

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#122]
please add this sir @exneval  in our custom script in idathena :(

https://rathena.org/board/topic/94194-stolaos-auto-event-v200/
https://github.com/Stolao/Npc_Release/tree/master/PvP_Ladder

when i try to use this script many errors and not working properly :(

**Comment by ernestfegarido** [comment]
some scripts in rathena are not working properly in idathena.

**Comment by ernestfegarido** [comment]
please update our npc emulator sir! make it like rathena :) so i can use script releases from rathena :)

**Comment by exneval** [comment]
will check where I should start, thank you

**Comment by ernestfegarido** [comment]
ty so much master @exneval !

**Comment by ernestfegarido** [comment]
up for this! :)

**Comment by ernestfegarido** [comment]
next proj pls! :)

**Comment by exneval** [comment]
@ernestfegarido  can I talk to you outside github? Here's my fb: www.facebook.com/exneval

**Comment by ernestfegarido** [comment]
i already added you sir @exneval :)
