### ISSUE TITLE
compile error (windows)

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#139]
latest rev
using windows 10 updated
using visual 2010

errors:
1>------ Build started: Project: map-server_sql, Configuration: Release Win32 ------
2>------ Build started: Project: login-server_sql, Configuration: Release Win32 ------
3>------ Build started: Project: char-server_sql, Configuration: Release Win32 ------
4>------ Build started: Project: mapcache, Configuration: Release Win32 ------
2>  grammar.c
2>  libconfig.c
2>  scanctx.c
2>  scanner.c
1>  grammar.c
1>  libconfig.c
1>  scanctx.c
1>  scanner.c
4>  core.c
4>  des.c
4>  grfio.c
4>  malloc.c
3>  grammar.c
3>  libconfig.c
3>  scanctx.c
3>  scanner.c
4>  showmsg.c
2>  strbuf.c
4>  strlib.c
1>  strbuf.c
2>  mt19937ar.c
2>  conf.c
1>  mt19937ar.c
4>  utils.c
3>  strbuf.c
2>  mempool.c
3>  mt19937ar.c
1>  conf.c
2>  mutex.c
1>  core.c
1>  db.c
3>  conf.c
3>  core.c
2>  raconf.c
4>  mapcache.c
2>  thread.c
3>  db.c
1>  des.c
3>  ers.c
1>  ers.c
3>  malloc.c
1>  grfio.c
3>  mapindex.c
2>  core.c
1>  malloc.c
1>  mapindex.c
2>  db.c
1>  md5calc.c
3>  mempool.c
4>  Generating code
1>  mempool.c
3>  mutex.c
2>  ers.c
3>  nullpo.c
2>  malloc.c
1>  mutex.c
4>  Finished generating code
3>  raconf.c
1>  nullpo.c
3>  random.c
2>  md5calc.c
1>  raconf.c
2>  nullpo.c
1>  random.c
2>  random.c
2>  showmsg.c
2>  socket.c
3>  showmsg.c
2>  sql.c
3>  socket.c
3>  sql.c
1>  showmsg.c
1>  socket.c
1>  sql.c
3>  strlib.c
1>  strlib.c
2>  strlib.c
3>  thread.c
2>  timer.c
3>  timer.c
2>  utils.c
1>  thread.c
1>  timer.c
2>  msg_conf.c
3>  utils.c
2>  cli.c
1>  utils.c
2>  account_sql.c
3>  msg_conf.c
2>  ipban_sql.c
3>  cli.c
1>  msg_conf.c
2>  login.c
3>  char.c
3>  int_auction.c
1>  cli.c
3>  int_elemental.c
2>  loginlog_sql.c
1>  atcommand.c
1>  battle.c
1>  battleground.c
3>  int_guild.c
1>  buyingstore.c
4>  mapcache.vcxproj -> D:\Users\Ernest\Downloads\Thor\Emulator\vcproj-10\..\mapcache.exe
3>  int_homun.c
3>  int_mail.c
3>  int_mercenary.c
3>  int_party.c
1>..\src\map\battle.c(5964): error C2065: 'NPC_HELLBURNING' : undeclared identifier
1>..\src\map\battle.c(5964): error C2051: case expression not constant
1>..\src\map\battle.c(6585): error C2065: 'NPC_MAXPAIN_ATK' : undeclared identifier
1>..\src\map\battle.c(6585): error C2051: case expression not constant
1>..\src\map\battle.c(7484): error C2065: 'NPC_MAXPAIN_ATK' : undeclared identifier
1>  cashshop.c
3>  int_pet.c
2>  Generating code
3>  int_quest.c
1>  channel.c
3>  int_storage.c
1>  chat.c
3>  inter.c
1>  chrif.c
1>  clif.c
1>  date.c
1>  duel.c
1>  elemental.c
2>  Finished generating code
3>  Generating code
1>  guild.c
1>  intif.c
1>  itemdb.c
1>  log.c
1>  mail.c
1>  map.c
2>  login-server_sql.vcxproj -> D:\Users\Ernest\Downloads\Thor\Emulator\vcproj-10\..\login-server_sql.exe
1>  mapreg_sql.c
1>  homunculus.c
1>  instance.c
1>  mercenary.c
1>  mob.c
1>  npc.c
1>  npc_chat.c
1>  party.c
1>  path.c
1>  pc.c
1>  pc_groups.c
1>  pet.c
1>  quest.c
1>  script.c
1>  searchstore.c
1>  skill.c
1>  status.c
1>  storage.c
1>..\src\map\status.c(822): error C2065: 'NPC_MAXPAIN' : undeclared identifier
1>  trade.c
1>..\src\map\skill.c(3149): error C2065: 'NPC_MAXPAIN_ATK' : undeclared identifier
1>..\src\map\skill.c(4440): error C2065: 'NPC_MAXPAIN_ATK' : undeclared identifier
1>..\src\map\skill.c(4440): error C2051: case expression not constant
1>..\src\map\skill.c(6117): error C2065: 'NPC_MAXPAIN' : undeclared identifier
1>..\src\map\skill.c(6117): error C2051: case expression not constant
1>..\src\map\skill.c(11473): error C2065: 'NPC_HELLBURNING' : undeclared identifier
1>..\src\map\skill.c(11473): error C2051: case expression not constant
1>  unit.c
1>  vending.c
3>  Finished generating code
3>  char-server_sql.vcxproj -> D:\Users\Ernest\Downloads\Thor\Emulator\vcproj-10\..\char-server_sql.exe
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by exneval** [comment]
Yes, it will be error if you use older client than 2014 02 05,
