### ISSUE TITLE
horror toy factory error

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#141]
i got this error im using latest rev compiled with vs 2010 im using 20120410a ragexere:

[Error]: script:instance_npcname: invalid instance NPC (instance_id: 0, NPC name: "#alert1".)
[Debug]: Source (NPC): alert#71 at 1@xm_d (110,44)

**Comment by ernestfegarido** [comment]
also the sprite is "4_F_SKULL06GIRL" but what i saw in game they are poring instead of "4_F_SKULL06GIRL"

**Comment by ernestfegarido** [comment]
is that because im using lower client date?

**Comment by exneval** [comment]
@ernestfegarido yes it might be.. Horror Toy Factory were added in kRO in 2012-12-18

**Comment by exneval** [comment]
Since the NPC become poring in 20120410, you can't enter the instance and warp to the map by using GM commands, that error has nothing to do with that.. Maybe start to use newer client?
