### ISSUE TITLE
Rebellion Skills not consumes coins correctly

### ISSUE THREAD

**Issue by poporing** [idathena/trunk#17]
Platinum Altar, Hit Barrel and God's Hammer should consumes all your Coins.
http://www.playragnarok.com/news/updatedetail.aspx?id=272
http://irowiki.org/wiki/Vanishing_Buster
http://irowiki.org/wiki/Hammer_of_God
http://irowiki.org/wiki/Heat_Barrel

**Comment by exneval** [comment]
Working as intended, those three skills consumed all coins.
