### ISSUE TITLE
rathena update

### ISSUE THREAD

**Issue by poporing** [idathena/trunk#304]
is it possible to add this update? https://github.com/rathena/rathena/commit/e59cdfff903c1f7ea920858eb62a6ce1b31db9c6

I try to help adding the mob loots https://github.com/idathena/trunk/pull/303

**Comment by poporing** [comment]
I try to help adding the mob loot https://github.com/idathena/trunk/pull/303

**Comment by exneval** [comment]
I will try, thanks

**Comment by poporing** [comment]
Here looks to be all update related to this, I shord them by date:
https://github.com/rathena/rathena/commit/f296409ada211a0aa89863db4d9603054845cf65
https://github.com/rathena/rathena/commit/e2bf685a8681903c775910f10d21f2bf6624f1d7
https://github.com/rathena/rathena/commit/8da71a126d800c4b4d36ce8937491098925d27d2
https://github.com/rathena/rathena/commit/0569d85dbfc8582f62e6dd9b8078aa080344a486
https://github.com/rathena/rathena/commit/3b09de10e9b254c1600554b7bb0c1319d151428e
https://github.com/rathena/rathena/commit/5a5621073fad76aed6b1051ceec2a79f5219a792
https://github.com/rathena/rathena/commit/01b105257095b59f250a75c10508d32100f3524e
https://github.com/rathena/rathena/commit/09cb81d98ed652f7f88e96ef90976776d10a9d65
https://github.com/rathena/rathena/commit/c3a308ffdb85f933af3596e4b0dc723be249c76b
https://github.com/rathena/rathena/commit/e655a73815a93d2d44140a7b2f5cd327d9919b8b
https://github.com/rathena/rathena/commit/e59cdfff903c1f7ea920858eb62a6ce1b31db9c6
https://github.com/rathena/rathena/commit/a15661ecfab06146485731fc9e4ce64ccce2606c

**Comment by poporing** [comment]
Could I help you to add this? I really want to use this features :D

**Comment by exneval** [comment]
I'm working on it already 😸

**Comment by poporing** [comment]
Thanks =) you are awsome

**Comment by exneval** [comment]
Dont forget to backup everything, just in case..
