### ISSUE TITLE
Received unknow packet

### ISSUE THREAD

**Issue by poporing** [idathena/trunk#314]
Hi,
When try to create a new char I receive this error
[Error]: parse_char: Received unknown packet 0xa39 from ip '127.0.0.1'! Disconnecting!

I'm using renewal config with client 
2015-09-16Ragexe

Last Git version

**Comment by poporing** [comment]
I try to find 2016-12-28eRagexeRE but can't find this client anywhere
isn't is a typo error 2016-12-28"a"RagexeRE?

**Comment by exneval** [comment]
You're right that's a typo should be 'a' instead of 'e' for 2016 client
And I thought the a39 packet should be started with 20151104, 20150916 still use the old one..
Why the error is appearing.. let me test it

**Comment by exneval** [comment]
Just tested with 20150916 and I don't have the issue while creating a new char...
maybe you forgot to set the PACKETVER in mmo.h to 20150916

**Comment by poporing** [comment]
Sorry just find that was my nemo have issue... Duno what happen... sorry
