### ISSUE TITLE
Atk2 of mob

### ISSUE THREAD

**Issue by poporing** [idathena/trunk#322]
Hi,
Is that normal that Atk2 is that low?
exemple poring have an atk of 8 and atk2 of 1
in divine-pride it's 8-9
I know aegis files use as you did but did the source are correct?

**Comment by exneval** [comment]
it is intended, atk2 in mob_db.txt isnt recognize as maximun attack, but as variance of mob matk calculation, idAthena merge this Aegis behavior from Hercules

**Comment by poporing** [comment]
ok thanks
