### ISSUE TITLE
Add Rodex

### ISSUE THREAD

**Issue by poporing** [idathena/trunk#323]
Hi,
is it possible to add new Rodex?
https://github.com/rathena/rathena/commit/58776da1ac14a46d3c717c72ddf2b7f2876f7392
https://github.com/rathena/rathena/commit/9d7d368a336ed90a3342665ea55525f94e1b0346
Thanks =)

**Comment by exneval** [comment]
I'm planning to add this feature, please wait for a while..

**Comment by Michieru** [comment]
thanks =)
