### ISSUE TITLE
Enable VIP

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#327]
![image](https://user-images.githubusercontent.com/4651777/27822003-c5ada38c-60d6-11e7-9f40-3bba6264926a.png)

when i enable VIP and compile it some error occurred
compiled using visual c++ 2010 express

**Comment by exneval** [comment]
They're warnings, not error.
Thanks for reporting.

**Comment by ernestfegarido** [comment]
![image](https://user-images.githubusercontent.com/4651777/27860916-3b652d72-61b1-11e7-8323-d80e31ebb08c.png)

sir egi still 1 warning occurred

**Comment by exneval** [comment]
yes, I realized it yesterday, my fault, will fixed in next commit.. thank you...
