### ISSUE TITLE
doram normal attack

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#329]
![image](https://user-images.githubusercontent.com/4651777/27861501-afd54ba4-61b3-11e7-8278-6f6b664bb971.png)

is doram really a range job?

**Comment by ernestfegarido** [comment]
im using latest rev compiled using visual c++ express 2010

**Comment by exneval** [comment]
Please update your lua files so you can see the new skill tree branch
I guess you don't know about doram new skill SU_SOULATTACK

[http://irowiki.org/wiki/Soul_Attack](url)

**Comment by ernestfegarido** [comment]
where can i get the latest data folder for renwal sir egi? right now im using zackdreaver's re folder.

**Comment by exneval** [comment]
It's ok to use zackdreaver, but please use [this file instead for Rebellion Awakening and Doram new skill patches](https://github.com/zackdreaver/ROenglishRE/tree/master/data/luafiles514/lua%20files/skillinfoz/RebellionRE)

**Comment by ernestfegarido** [comment]
thanks for the info sir egi!
