### ISSUE TITLE
Skill

### ISSUE THREAD

**Issue by Lokyluminiaro** [idathena/trunk#346]
Hello, I inform you 2 skills of bugs.

1st: Skill Release of the Warlock class which within a delay after the casting the skill Release.

2nd: The skill Fallen angel of the class Rebelion that makes a blody reloc (of the class champion) instead of making a jump + desperados.

Thank you in advance ! 

Loky

**Comment by exneval** [comment]
Hi there,
for 1st: it's intended, the aspd of warlock will determine the delay of releasing spell
for 2nd: it's also intended, idA already implemented Rebellion's Awakening Patch from kRO
thank you

**Comment by Lokyluminiaro** [comment]
Simply attend the correction of both skills?
Can you tell me an average time?

Thank you !

2017-07-25 20:42 GMT+02:00 Egi Ginting <notifications@github.com>:

**Comment by exneval** [comment]
the delay between release and released spell will be same like the warlock basic attack delay

**Comment by Lokyluminiaro** [comment]
Hi,

Sorry to disturb you again!

This is to signal you that an item bug (Eden Group Mark ID22508)

If a player uses it during the cooldown (20 min) the server map crash.

I'm still looking for the mistake! If I find, I send you an email with the
correction.

thank you

Loky

2017-07-25 20:56 GMT+02:00 Egi Ginting <notifications@github.com>:

**Comment by exneval** [comment]
I can't reproduce the eden group mark issue, please let me know if you already know who to produce the map server crash, and if you're using linux, you can always provide me the gdb dump of the crash

**Comment by Lokyluminiaro** [comment]
Hello, I found the problem of the server crash related to the item. Its
come from file item_delay.txt (db / re)
The server did not like this line: 22508,1200000 // Para_Team_Mark_

2017-07-27 11:45 GMT+02:00 Egi Ginting <notifications@github.com>:

**Comment by exneval** [comment]
Please give me the steps how to produce the crash, thanks
