### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by Lokyluminiaro** [idathena/trunk#367]
Hi,

I have a translation problem with a rathena script. I can not change the trader. I let you see:

moro_cav,32,73,5	trader	Hero Token Exchanger	1_M_MERCHANT,{
	
	OnInit:
	tradertype(NST_CUSTOM);
	sellitem 2981,30;
	end;

OnCountFunds:
	setcurrency(countitem(6684));
	npctalk "I will trade you these items for your Tokens of Hero.";
	end;

OnPayFunds:
	if( countitem(6684) < @price ) {
		npctalk "You do not have enough Tokens of Hero for that.";
		end;
	}
	delitem 6684,@price;
	purchaseok();
	end;
}

If the translation is corrected, I can provide you with quests 14.3.

**Comment by exneval** [comment]
I believe that is Herc script, for rA/idA i guess you meant of 'itemshop'?

**Comment by Lokyluminiaro** [comment]
Problem solve, thx ;)
