### ISSUE TITLE
Throw Kunai requires Shuriken instead of Kunai

### ISSUE THREAD

**Issue by magimagica** [idathena/trunk#369]
Hash: c80a645c005725aa269f0300254defb3476a71b7
Client: 2017-05-17bRagexeRE
Mode: Renewal
Issue: Throw Kunai requires Shuriken instead of Kunai
and I can't equip Kunai?

Haven't tested on prerenewal

**Comment by exneval** [comment]
Will check it

**Comment by exneval** [comment]
Just tested fine, please test again

**Comment by magimagica** [comment]
Yes, but Shuriken still can be used to throw Kunai.

**Comment by exneval** [comment]
I'll test it once again

**Comment by exneval** [comment]
I didn't able to reproduce the issue, i need to equip the kunai to be able to cast the skill, no matter what the equipped weapon is, can you describe the issue more detail, maybe provide some screen shots?
