### ISSUE TITLE
Any work in progress

### ISSUE THREAD

**Issue by Lokyluminiaro** [idathena/trunk#375]
Hi,

I post today for an NPC worry. I'll let you look for yourself.

https://www.youtube.com/watch?v=OYebrfrLE6I

Could this come from the switch menu? my warper script uses the MENU system and has no worries! All scripts using the switch function have problems.

No changes have been made to the sources.

**Comment by exneval** [comment]
will check first

**Comment by poporing** [comment]
same issue as https://github.com/rathena/rathena/issues/2177
Since you use rathena as base you got the same issue.

**Comment by exneval** [comment]
as in that issue told us, please avoid to attach player or using sleep2 in pcloginevent label, will be fixed along with rA update
