### ISSUE TITLE
Dress room

### ISSUE THREAD

**Issue by zackdreaver** [idathena/trunk#384]
Hash: c1e022995d31b9a7332217525f4c4314d9fb0af5
Client: 2016-12-28aRagexeRE
When I use https://github.com/3CeAM/3CeAM/blob/master/rewrite/npc/3ceam/3ceam_stylist.txt
I get this error
![dresserror](https://user-images.githubusercontent.com/10024221/30784261-5e1b1e8e-a17c-11e7-82fc-c0d4d8ec533a.jpg)

**Comment by exneval** [comment]
Wasn't able to produce the issue using the same client and script, please check it again

**Comment by zackdreaver** [comment]
sometime it'll gives this error on console when changing body style. It's kinda rare to happen though

**Comment by exneval** [comment]
Actually using raw 3ceam super stylist itself in idA will not working, please use [this](https://rathena.org/board/files/file/3493-super-stylist-dress-room-required/) instead, only need to change EAJ_THIRD into EAJ_THIRDMASK and remove the blacklist variable and check should make it work

**Comment by zackdreaver** [comment]
Ok, thanks for suggestion
