### ISSUE TITLE
[CENTOS 64BIT] WARNING/ERROR COMPILING

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#418]
hi sir ex, please see attached file. thank you.

using clean latest rev.
![warning 1](https://user-images.githubusercontent.com/4651777/32988216-60d23c54-cd3a-11e7-84f8-69c6cc0f662d.PNG)

**Comment by exneval** [comment]
Should be fixed in a82b2f1

**Comment by ecdarreola** [comment]
@ernestfegarido : how do you compile on a 64bit centos?

regards
