### ISSUE TITLE
Wshadow compile warnings

### ISSUE THREAD

**Issue by ecdarreola** [idathena/trunk#431]
Hi Enex,

I'm having problem compiling using g++ & gcc 7. Is there a tutorial for installation in linux centos?

Regards!

**Comment by exneval** [comment]
try
./configure
make clean
make sql

**Comment by ecdarreola** [comment]
@exneval : Will try sir.

**Comment by ecdarreola** [comment]
Got a lot of errors using devtoolset-7 sir @exneval 

/opt/rh/devtoolset-7/root/usr/bin/ar: obj/grammar.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj/libconfig.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj/scanctx.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj/scanner.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj/strbuf.o: plugin needed to handle lto object

grfio.c: In function ‘grfio_find_file’:
grfio.c:303:12: warning: declaration of ‘filelist’ shadows a global declaration [-Wshadow]
  FILELIST *filelist = filelist_find(fname);
            ^~~~~~~~
grfio.c:48:11: note: shadowed declaration is here
 FILELIST* filelist  = NULL;

/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/core.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/socket.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/timer.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/db.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/nullpo.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/malloc.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/showmsg.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/strlib.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/utils.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/grfio.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/mapindex.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/ers.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/md5calc.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/minicore.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/minisocket.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/minimalloc.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/random.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/des.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/conf.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/thread.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/mutex.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/raconf.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/mempool.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/msg_conf.o: plugin needed to handle lto object
/opt/rh/devtoolset-7/root/usr/bin/ar: obj_all/cli.o: plugin needed to handle lto object

Is it because of the toolset that i'm using?

**Comment by exneval** [comment]
Sorry for late reply,
well it could be, can you try it with another version of it, maybe with the lower version? The installation should be same like the old way one, cause I never have a chance to update it

**Comment by ecdarreola** [comment]
@exneval which toolset should I use? Should it be 4 or 3?

**Comment by ecdarreola** [comment]
I tried toolset 3 and 4 sir @exneval but all have error.

**Comment by exneval** [comment]
can you try with lower version of gcc? maybe 5?

**Comment by ecdarreola** [comment]
@exneval i already tried lower gcc sir. 4.9 not working

**Comment by exneval** [comment]
how about
./configure --enable-lto=yes

**Comment by ecdarreola** [comment]
@exneval devtoolset-3 works for me but error in compiling:

![image](https://user-images.githubusercontent.com/5693492/33588902-4fb31204-d9b0-11e7-8f76-b00a5dc50c07.png)

![image](https://user-images.githubusercontent.com/5693492/33588907-57651eca-d9b0-11e7-827c-d9e58870aaea.png)

Also this one.

**Comment by exneval** [comment]
let me fix that one, please wait a minute

**Comment by exneval** [comment]
can you please try the new updates? @ecdarreola

**Comment by ecdarreola** [comment]
I still have an error sir @exneval 
![image](https://user-images.githubusercontent.com/5693492/33589584-622cdde4-d9b4-11e7-93ef-eefa76e88801.png)

**Comment by exneval** [comment]
are you using 64 bit?
if yes please try
./configure --enable-64bit
make clean
make sql

**Comment by ecdarreola** [comment]
Still the same sir @exneval after using --enable-64bit
![image](https://user-images.githubusercontent.com/5693492/33589694-4a102382-d9b5-11e7-8479-e00ebe6911eb.png)

**Comment by exneval** [comment]
can you try
./configure --disable-lto

**Comment by ecdarreola** [comment]
It worked @exneval but so many warnings of shadows

![image](https://user-images.githubusercontent.com/5693492/33590711-2343f470-d9bc-11e7-99c9-aee754eb95b5.png)

Also this error:

![image](https://user-images.githubusercontent.com/5693492/33590734-3c01ae12-d9bc-11e7-924b-eba590a2d16d.png)

**Comment by exneval** [comment]
have you try to update the gcc?

**Comment by ecdarreola** [comment]
@exneval : which devtoolset should I use or gcc should I use?

**Comment by ecdarreola** [comment]
I used this @exneval 
![image](https://user-images.githubusercontent.com/5693492/33590970-88752318-d9bd-11e7-91d0-02c17feeeb10.png)

![image](https://user-images.githubusercontent.com/5693492/33590977-91dc30ea-d9bd-11e7-97bb-43f305958d5f.png)

**Comment by exneval** [comment]
ok first, just ignore the warning for now,
and then try to recompile, make sure you do the 'make clean' before the 'make sql'

**Comment by ecdarreola** [comment]
Here's what results after using the make clean and make sql (while ignoring the warning)

![image](https://user-images.githubusercontent.com/5693492/33591042-099191fc-d9be-11e7-96e3-35cc97254946.png)

**Comment by exneval** [comment]
can you try to edit this file?
...\src\test\Makefile.in
find
COMMON_DIR_OBJ = $(COMMON_OBJ:%=../common/obj/%)
replace to
COMMON_DIR_OBJ = $(COMMON_OBJ:%=../common/obj_all/%)

**Comment by ecdarreola** [comment]
@exneval Can't find such parameters or entry. in \src\test\Makefile.in file.

**Comment by exneval** [comment]
@ecdarreola i just edited the post, it's src\tool\

**Comment by exneval** [comment]
How is it? @ecdarreola

**Comment by ecdarreola** [comment]
@exneval Worked great! Using ./configure --disable-lto and changing the makefile.in but lots of warning.

[warning.txt](https://github.com/idathena/trunk/files/1529800/warning.txt)

Should it be normal?

**Comment by exneval** [comment]
@ecdarreola those warnings should not be a problem, I'll fixed it as soon as possible

**Comment by ecdarreola** [comment]
@exneval : Should I close this issue and recreate a new one? Just for the warning?

**Comment by exneval** [comment]
no need for that
