### ISSUE TITLE
Pet Evolution

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#434]
now there are Packet：
	// Pet Evolution System
	parseable_packet(0x09FB,-1,clif_parse_dull,0); // CZ_PET_EVOLUTION
	packet(0x09FC,6); // ZC_PET_EVOLUTION_RESULT
but it's not functional.
Could you please activate it?
thanks a lot

**Comment by exneval** [comment]
The community still lack of information about the structure, it will be implemented when there's more info about it

**Comment by idamonli** [comment]
https://github.com/HerculesWS/Hercules/pull/2063
Is this portable?
