### ISSUE TITLE
Lapine Upgrade

### ISSUE THREAD

**Issue by ghost** [idathena/trunk#447]
On the geffen official magic tournament, the geffen enchanter NPC is missing.

**Comment by exneval** [comment]
@ecdarreola  this npc update just came recently in kRO, since iRO still not have it, we're still need all of the information about it, and also the english text, but I'll confirm it, to work with it asap

**Comment by burwinkelito** [comment]
https://www.divine-pride.net/forum/index.php?/topic/3378-kro-geffen-magic-tournament-and-ghost-palace-enchant/&tab=comments#comment-4897

**Comment by exneval** [comment]
Implemented the Lapine Upgrade Function
