### ISSUE TITLE
Hoping for updates

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#455]
still looking forward for updates! :)

**Comment by exneval** [comment]
Will add it soon..

**Comment by idamonli** [comment]
What are you up to recently?

**Comment by exneval** [comment]
I'm currently doing some skill official behavior updates. Then I'll proceed to clients version updates. Please wait for it

**Comment by Miraakol** [comment]
can't wait for the latest updates! @exneval thank you for continuing this project!

**Comment by exneval** [comment]
Please check the new updates

**Comment by Miraakol** [comment]
Thanks sir exneval! Pls also add new instances pls! Again thank you!

**Comment by exneval** [comment]
sure

**Comment by Miraakol** [comment]
Sorry for bothering you. Also please please make rathena script releases compatible with idathena since rathena is the most active forum when it comes to custom scripts.

**Comment by exneval** [comment]
can you give me some examples? any errors in map console?

**Comment by Miraakol** [comment]
I give you updates later when i get home. Really appreciate your work. Pls continue to update this project! Thank you sir exneval!

**Comment by exneval** [comment]
great, thank you

**Comment by Miraakol** [comment]
Question sir ex, what client dates are compatible with idathena?

**Comment by exneval** [comment]
currently it is up to 2017-12-13bRagexeRE

**Comment by exneval** [comment]
yes.. should also support older client

try this [link](http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/)

**Comment by Miraakol** [comment]
Thanks for the link! Will try this later!

**Comment by exneval** [comment]
@Miraakol  @idamonli  Please test idAthena recent updates of Pet Evolution

**Comment by Miraakol** [comment]
@exneval will try this later when i get home. thanks for new updates! how about the compile warning did you fixed it already?
