### ISSUE TITLE
BUG break;

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#462]
switch(select("AAA:bbb")) {...................................

	case 2:
	   break;
The script cannot proceed~

![qq 20180907220818](https://user-images.githubusercontent.com/13962741/45223750-b09d7280-b2ea-11e8-93f0-f0b9457abba9.png)

**Comment by exneval** [comment]
You need to give more details, can you give an complete example script?

**Comment by exneval** [comment]
@idamonli can you give me more info about this issue?

**Comment by idamonli** [comment]
mid_camp,207,290,6	script	次元裂缝导览员#01	4_M_EIN_SOLDIER,{
	mes "[远征队员 菲尔]";
	mes "真的要进入次元裂缝吗?";
	mes "请使用这边的机关。";
	next;
	switch(select("何谓次元裂缝?:结束对话。")) {
	case 1:
		mes "[远征队员 菲尔]";
		mes "我们不是透过此裂缝进出这里和米德加尔特吗?";
		mes "你可以把次元裂缝想成他的升级版。";
		next;
		mes "[远征队员 菲尔]";
		mes "有人发现了透过次元裂缝通往各裂缝的道路。";
		next;
		mes "[远征队员 菲尔]";
		mes "最近刚完成安全性的测试终于开放通行了。";
		mes "因此可更快速地前往彩虹桥、梦罗克、艾尔迪?斯特等地了。";
		next;
		mes "[远征队员 菲尔]";
		mes "次元裂缝势时间和空间失真的地方，";
		mes "万一迷路时不知会掉落何处，所以只能去已通过检验的地方。";
		next;
		mes "[远征队员 菲尔]";
		mes "若在里面迷路就永远找不到路啰!";
		close;
	case 2:
	   break;
	}
}

**Comment by exneval** [comment]
You need to put
close;
After the
break;

**Comment by idamonli** [comment]
verus04,170,150,3	script	音盘#e152a01	CLEAR_NPC,{
	if ($@lp01on == 0) {
		if (ep15_1_atnad == 24) {
			mes "准备播放记忆音盘的语音信息。";
			$@lp01on = 1;
			sleep2 1000;
			npctalk "杂讯------ 嗡嗡嗡--- ";
			sleep2 3000;
			npctalk "嗡嗡-- 喂! 你干什么? 有听我说话吗?";
			sleep2 3000;
			npctalk "有在听杰雷特尔 .. 啊! 我的声音也被录进去了!";
			sleep2 3000;
			npctalk "什么? 现在录音中吗? 你想干吗?";
			sleep2 3000;
			npctalk "嗡嗡嗡---.. 什么? 建置中. 啊 ..嗡嗡嗡- 被录进去了。";
			sleep2 3000;
			npctalk "哈哈哈! 是吗? 果然是亚奈德. 嗡嗡嗡-- 呢?";
			sleep2 1000;
			npctalk "..亚奈德?","团长 艾昆妮#e152v01";
			sleep2 2000;
			npctalk "嗡嗡嗡-- 嗡嗡..这..家伙--- 欠揍.. 杂讯----";
			sleep2 3000;
			$@lp01on = 0;
			next;
			mes "储存于记忆音盘的全部语音信息播放完毕。";
			ep15_1_atnad = 25;
			close2;
		} else if (ep15_1_atnad == 28) {
			mes "播放记忆音盘的语音信息。";
			$@lp01on = 1;
			sleep2 1000;
			npctalk "我是桃萝西 佛罗伦丝，今天在监控事发现了一个记忆音盘。";
			sleep2 4000;
			npctalk "也许是实验当天的黑匣子~ 现在来播放!";
			sleep2 4000;
			npctalk "嗡嗡嗡-- 啊.. 一开始是杂音... 有声音了。";
			sleep2 4000;
			npctalk "祝好运..";
			sleep2 4000;
			npctalk "(女声) 啊.. 很遗憾没谈过恋爱。";
			sleep2 4000;
			npctalk "(其他女声) 啊.. 很可惜没有边吃边看这景况...嗡嗡嗡--";
			sleep2 4000;
			npctalk "哦? 没了吗? 这声音是送干洗衣物的尔特米额呢!";
			sleep2 4000;
			npctalk "..嗯..原来如此，那天结局是那样啊..... ";
			sleep2 4000;
			npctalk "达喀!";
			sleep2 3000;
			$@lp01on = 0;
			next;
			mes "储存于记忆音盘的全部语音信息播放完毕。";
			ep15_1_atnad = 29;
			if (countitem(22691) < 1 && countitem(22692) < 1 && countitem(22693) < 1 && countitem(22694) < 1 && countitem(22695) < 1) {
				getitem 22691,1;
				setquest 7653;
			}
			next;
			specialeffect EF_SPELLBREAKER;
			mes "当试图取出记忆音盘时, 连接的部分又重新断开,整个记忆音盘又变成了碎片状";
			close2;
		} else if (ep15_1_atnad > 29) {
			.@q7654 = isbegin_quest(7654);
			.@q7655 = isbegin_quest(7655);
			if (.@q7654 == 1) {
				mes "准备播放记忆音盘的语音信息。";
				$@lp01on = 1;
				sleep2 1000;
				switch(rand(1,14)) {
					case 1:
						npctalk "今天是贝鲁兹城第4885次计划的最后一次实验日。";
						sleep2 4000;
						npctalk "大家都希望成功一起去实验洞参观了。";
						sleep2 4000;
						npctalk "刚好我是研究洞的值班人员，所以没参加。";
						sleep2 4000;
						npctalk "还有拓堤奥也不是主计划的成员，所以跟我一起守着研究洞。";
						sleep2 4000;
						npctalk "虽感到有点凄凉.... 但期待能成功..";
						sleep2 4000;
						npctalk "刚才没闪光吗? 喂!";
						sleep2 4000;
						npctalk "轰隆! 嗡嗡嗡...";
						break;
					case 2:
						npctalk "你好拓堤奥，你能全部收集后听取吗?";
						sleep2 4000;
						npctalk "想到独自留在城镇的你我开了小玩笑。";
						sleep2 4000;
						npctalk "把我们的希望和绝望留给你深感抱歉。";
						sleep2 4000;
						npctalk "像地狱般的城镇里你要孤独的生活多久呢?";
						sleep2 4000;
						npctalk "为了你打算把记忆音盘藏起来。";
						sleep2 4000;
						npctalk "当然还有把它拆解开了~!";
						sleep2 4000;
						npctalk "希望你有机会找到它并听到它。";
						sleep2 4000;
						npctalk "...你的永远挚友拉瑟 亚奈德。";
						break;
					case 3:
						npctalk "你好，我是拉瑟 亚奈德，今天也在研究洞值班。";
						sleep2 4000;
						npctalk "哦? 这是..? 亚奈德你在干什么?";
						sleep2 4000;
						npctalk "你看不懂吗? 这是在录音啊!";
						sleep2 4000;
						npctalk "都什么时代了还在录音? 摄影啦摄影!";
						sleep2 4000;
						npctalk "你管我! 别妨碍我，竟然攻击我弱点，可恶! 哈哈!";
						sleep2 4000;
						npctalk "…嗡嗡..断!";
						break;
					case 4:
						npctalk "爆炸第一天，语音记录拉瑟 亚奈德。";
						sleep2 4000;
						npctalk "实验洞的实验判定为失败，贝鲁兹城自动开启了防灾设备。";
						sleep2 4000;
						npctalk "对外全面封锁，各区升起了隔墙阻绝。";
						sleep2 4000;
						npctalk "虽然系统正在快速修复中，但问题是对外联络中断。";
						sleep2 4000;
						npctalk "可能是贝鲁兹城自行判断发生了灾难吧!";
						sleep2 4000;
						npctalk "为了避免扩大伤害，跟对外分离后沉没中…";
						sleep2 4000;
						npctalk "………真是的…";
						sleep2 4000;
						npctalk "我并不想留下这类记录啦…";
						break;
					case 5:
						npctalk "再见! 我是希维亚 罗伦。";
						sleep2 4000;
						npctalk "喜欢吃炸鸡配啤酒。";
						sleep2 4000;
						npctalk "呜... 今天勉强承接了一个计划。";
						sleep2 4000;
						npctalk "老实说对此不太感兴趣。";
						sleep2 4000;
						npctalk "因为宾珊特也有参加。";
						sleep2 4000;
						npctalk "啊.......";
						sleep2 4000;
						npctalk "不小心说出本名了，怎么办?! 删掉它!! 嗡嗡~";
						break;
					case 6:
						npctalk "爆炸第32天，语音记录拉瑟 亚奈德。";
						sleep2 4000;
						npctalk "实验洞里的能源爆炸始终不停歇。";
						sleep2 4000;
						npctalk "参观及参与实验人员的生死是...";
						sleep2 4000;
						npctalk "目前除了连结安全室系统的生体反应之外都不得而知。";
						sleep2 4000;
						npctalk "广场和研究洞虽受爆炸时的波及，幸好受损不严重。";
						sleep2 4000;
						npctalk "但是.. 部分研究员和百姓却不幸罹难..";
						sleep2 4000;
						npctalk "目前利用研究洞的设备制造探勘机器人。";
						sleep2 4000;
						npctalk "因贝鲁兹城的主动力停止运转，所以启动备用能源电力好让基本设施正常运作。";
						sleep2 4000;
						npctalk "实验洞的隔墙对面仍受到能量风暴而无法靠近。";
						sleep2 4000;
						npctalk "受不了被城镇孤立的许多研究员开始主张研究时间滑移。";
						sleep2 4000;
						npctalk "…..反正在这里出不去，梦想时间回归也不错。";
						break;
					case 7:
						npctalk "再会!拓堤奥。";
						sleep2 4000;
						npctalk "大部分的人已经罹难。";
						sleep2 4000;
						npctalk "为了生存只好把它们火化，对此我心中并没有负罪感。";
						sleep2 4000;
						npctalk "我更担心的是独自留下的你。";
						sleep2 4000;
						npctalk "所以请不要难过。";
						sleep2 4000;
						npctalk "就在明天，我们将会全部撤离…";
						sleep2 4000;
						npctalk "希望后会有期~";
						break;
					case 8:
						npctalk "再见~ 拓堤奥!";
						sleep2 4000;
						npctalk "不知已过了多少年。";
						sleep2 4000;
						npctalk "赋予你永恒的生命也许是正确的。";
						sleep2 4000;
						npctalk "出外探勘队员的结局你也知道吧? 我也要出去生活。";
						sleep2 4000;
						npctalk "在科学文明消失的这地方，我要像太初的人类一样生活。";
						sleep2 4000;
						npctalk "放弃科学，改学魔法吧? 哈哈哈!";
						sleep2 4000;
						npctalk "啪! 别老说梦话了!";
						sleep2 4000;
						npctalk "啊.. 又被打到了..嗡嗡嗡.. 痛... 嗡嗡嗡";
						break;
					case 9:
						npctalk "灾害系统的荧幕上再也看不到安全室里生还者的人数。";
						sleep2 4000;
						npctalk "究竟是怎么回事呢?";
						sleep2 4000;
						npctalk "究竟发生了什么事? 是系统出错了吗?";
						sleep2 4000;
						npctalk "拓堤奥还认为Dr.普蕾莎活着。";
						sleep2 4000;
						npctalk "祈祷他的心脏不会痛...";
						break;
					case 10:
						npctalk "测试测试.. 哇.. 正常耶!";
						sleep2 4000;
						npctalk "你好! 我是软体工程师苏库立塔。";
						sleep2 4000;
						npctalk "今天要说明的是有关苏库塔引擎所使用的苏库塔语言的注意事项。";
						sleep2 4000;
						npctalk "苏库塔语言皆可使用全域变数和区域变数..";
						sleep2 4000;
						npctalk "其中全域变数如恶魔般一旦掉入全域变数的甜美诱惑陷阱的话...";
						sleep2 4000;
						npctalk "你会患对1Byte错误的空白键和特殊符号也会心动，";
						sleep2 4000;
						npctalk "及流冷汗的重症。";
						sleep2 4000;
						npctalk "下一堂课是苏库塔语言的替代方案，也是我发明的";
						sleep2 4000;
						npctalk "有关苏库立塔语言的说明，呵呵!";
						break;
					case 11:
						npctalk "printf(Hello, World!)";
						sleep2 4000;
						npctalk "end; 0";
						sleep2 4000;
						npctalk "到这里编码后射了10箭。";
						sleep2 4000;
						npctalk "费迪南多。";
						break;
					case 12:
						npctalk "喂! 拉瑟我有事要问你?";
						sleep2 4000;
						npctalk "啥事? 干嘛还把别人的录音机拿出来?";
						sleep2 4000;
						npctalk "这是采访，身为生命工学先驱者的我... ";
						sleep2 4000;
						npctalk "你想问什么? 什么啦?";
						sleep2 4000;
						npctalk "我想问拓堤奥大部分不是人造的吗? 听说那是Dr.普蕾莎的杰作，是真的吗?";
						sleep2 4000;
						npctalk "对，Dr.普蕾莎来贝鲁兹城之前是研究神经系机械置换的...";
						sleep2 4000;
						npctalk "所以那对情侣是因那件事相遇的吗?";
						sleep2 4000;
						npctalk "应该是吧? 据说拓堤奥毫不迟疑的答应做人体实验呢!";
						sleep2 4000;
						npctalk "嗯.. 难道那是单恋的结晶吗?";
						sleep2 4000;
						npctalk "啊? 那是什么意思? 怎么突然下那种结论，且又是别人的私事...";
						sleep2 4000;
						npctalk "把人分成可研究和不可研究的人是普蕾莎..";
						sleep2 4000;
						npctalk "突然某天带来号称是丈夫的人，确实吓一大跳呢?!?!?!";
						sleep2 4000;
						npctalk "所以你关心的不是生体工学，而是Dr.普蕾莎的恋爱史喔! 唉..";
						sleep2 4000;
						npctalk "对! 那木头人般的普蕾莎竟然有恋人..!! 你会相信吗?";
						sleep2 4000;
						npctalk "好了，别说了啦?";
						sleep2 4000;
						npctalk "啊! 拓堤奥你什么时后来的，哈哈! 没事!";
						sleep2 4000;
						npctalk "轰砰砰---!  啪嗒!";
						break;
					case 13:
						npctalk "我是属于研究所需的人。";
						sleep2 4000;
						npctalk "至少我对她的价值是那样，这我早已明白。";
						sleep2 4000;
						npctalk "而我仍无法拒绝的理由是似乎被她迷住，只能顺从她而已...";
						sleep2 4000;
						npctalk "因为我心脏的主人是她的缘故...";
						sleep2 4000;
						npctalk "沙沙响!";
						sleep2 4000;
						npctalk "呼.. 果然如此，是单恋没错。";
						sleep2 4000;
						npctalk "哦? 前辈你在看... 那不是拓堤奥日记本吗?";
						sleep2 4000;
						npctalk "安静! 被发现怎办!";
						sleep2 4000;
						npctalk "哇! 你边念边录音喔?!?!?!?!";
						break;
					case 14:
						npctalk "喀嚓-嗡嗡 不要拦我，哈哈，我要记录下来";
						sleep2 4000;
						npctalk "噗哈哈哈哈!";
						sleep2 4000;
						npctalk "我不是发疯，只是太好笑了，哈哈哈!";
						sleep2 4000;
						npctalk "现在是好笑的时候吗?";
						sleep2 4000;
						npctalk "当然不是，只是，呵呵呵....";
						sleep2 4000;
						npctalk "…那要哭吗? 嗯? 反而有希望不是吗?";
						sleep2 4000;
						npctalk "我们的希望啊!";
						sleep2 4000;
						npctalk "啪-! 啊… 这.. 这一击是杰雷特…..";
						sleep2 4000;
						npctalk "唉! 你欠揍喔!";
						sleep2 4000;
						npctalk "哦? 是在录音吗?";
						break;
				}
				sleep2 3000;
				$@lp01on = 0;
				next;
				mes "储存于记忆音盘的全部语音信息播放完毕。";
				erasequest 7650;
				erasequest 7654;
				setquest 7651;
				getexp 1500000,1000000;
				if (ep15_2_permit < 5) {
					ep15_2_permit += 1;
				}
				next;
				specialeffect EF_SPELLBREAKER;
				mes "当试图取出记忆音盘时, 连接的部分又重新断开,整个记忆音盘又变成了碎片状";
				next;
				cutin "Arquien_n_atnad01", 2;
				mes "[奈伊]";
				mes "其实播放的内容只有一段, 但是每次播到一半就会变成碎片,";
				mes "看来是有人故意这么设计的,";
				mes "每次都要重新整理, 真麻烦..";
				next;
				mes "[奈伊]";
				mes "明明有很高的科技水平, 为什么要这样设计呢?";
				mes "而且其中还有重复的内容..";
				mes "我看一定是有人故意阻止别人去挖掘过去的事.";
				next;
				mes "[奈伊]";
				mes "这内容我会另外记录后交给父亲，";
				mes "今天也辛苦你了。";
				next;
				if (ep15_2_permit == 5) {
					mes "[奈伊]";
					mes "等等，感觉到一股不寻常的氛围呢?";
					mes "那个帐篷就是考古队的所在地吧?";
					mes "好像有人造访呢?";
					mes "快去看看吧!";
					ep15_2_permit =  6;
					close2;
				} else {
					mes "[奈伊]";
					mes "明天再来找我吧!";
					close2;
				}
			} else if (.@q7655 == 1) {
				mes "准备播放记忆音盘的语音信息。";
				$@lp01on = 1;
				sleep2 1000;
				switch(rand(1,18)) {
					case 1:
						npctalk "我是桃萝西 佛罗伦丝，这可怕的事故...";
						sleep2 4000;
						npctalk "我认为应该把它纪录下来，所以对此我进行了录音。";
						sleep2 4000;
						npctalk "因为实验所引起的大爆炸，建筑的外层已彻底崩塌。";
						sleep2 4000;
						npctalk "大部分人已进入安全室避难。";
						sleep2 4000;
						npctalk "与外界的联络也被切断了。";
						sleep2 4000;
						npctalk "看来暂时没办法出去了。";
						break;
					case 2:
						npctalk "我是桃萝西 佛罗伦丝，爆炸第二天，目前状况还非常混乱。";
						sleep2 4000;
						npctalk "对总策划人兼首席研究员的Dr.普蕾莎...";
						sleep2 4000;
						npctalk "人们的责难纷至沓来。";
						sleep2 4000;
						npctalk "其实这不是一个人所该承担的责任。";
						sleep2 4000;
						npctalk "他们应该是想找替罪羔羊吧!";
						break;
					case 3:
						npctalk "我是桃萝西 佛罗伦丝，已是第三天的晚上。";
						sleep2 4000;
						npctalk "有别于昨天的责难，今天大家却推举Dr.普蕾莎来收拾残局。";
						sleep2 4000;
						npctalk "生命工学, 机械工学, 设备小组等.. 该有的人都有。";
						sleep2 4000;
						npctalk "当然还有像我这样在厨房工作的基层人员。";
						sleep2 4000;
						npctalk "我只是来送干洗的衣物而已呢。";
						sleep2 4000;
						npctalk "我怎么也被卷入进去了呢?";
						break;
					case 4:
						npctalk "我是桃萝西 佛罗伦丝。";
						sleep2 4000;
						npctalk "在Dr.普蕾莎的指挥下大家各就各位了。";
						sleep2 4000;
						npctalk "我们在外面的能量风暴停止前必须在这里生活。";
						sleep2 4000;
						npctalk "粮食问题则采纳了餐厅老板的建议。";
						sleep2 4000;
						npctalk "据说库存的粮食可维持40天。";
						sleep2 4000;
						npctalk "这间安全室真不简单。";
						break;
					case 5:
						npctalk "我是桃萝西 佛罗伦丝。";
						sleep2 4000;
						npctalk "生物学家所培养的植物终于发芽了耶!";
						sleep2 4000;
						npctalk "难道不值得开心吗?";
						sleep2 4000;
						npctalk "虽然如此，但是目前依然无法跟外界取得联络。";
						sleep2 4000;
						npctalk "已过去一周了，目前安全室里的人唯一的乐趣就是...";
						sleep2 4000;
						npctalk "看着植物发芽, 茁壮成长。";
						break;
					case 6:
						npctalk "我是桃萝西 佛罗伦丝，今天是在安全室生活满一个月的日子。";
						sleep2 4000;
						npctalk "因为空气净化器故障而让大家手忙脚乱。";
						sleep2 4000;
						npctalk "只会洗衣的我，能做的只有干瞪眼...";
						sleep2 4000;
						npctalk "还好已经有人做好了备用的空气净化器...";
						sleep2 4000;
						npctalk "所以呼吸应该没什么问题。";
						sleep2 4000;
						npctalk "真是不幸中的大幸啊!";
						break;
					case 7:
						npctalk "我是桃萝西 佛罗伦丝。";
						sleep2 4000;
						npctalk "今天举行了一场小型庆祝会。";
						sleep2 4000;
						npctalk "因为培养的植物上终于能够收获果实了!";
						sleep2 4000;
						npctalk "据生命工程学的人说....";
						sleep2 4000;
						npctalk "利用成长促进技术至少2周可收获一次。";
						sleep2 4000;
						npctalk "今天终能尝到美味的葡萄咯!";
						break;
					case 8:
						npctalk "我是桃萝西 佛罗伦丝，过了一个月带一周了。";
						sleep2 4000;
						npctalk "今天有坏消息。";
						sleep2 4000;
						npctalk "到外面测量大气数据的人没能回来。";
						sleep2 4000;
						npctalk "可能都凶多吉少吧!";
						sleep2 4000;
						npctalk "愿他们安息。";
						break;
					case 9:
						npctalk "我是桃萝西 佛罗伦丝，爆炸发生后第44天。";
						sleep2 4000;
						npctalk "在防护墙内有一部分人变得十分奇怪。";
						sleep2 4000;
						npctalk "可能和有人到外面去的事有关。";
						sleep2 4000;
						npctalk "于是大家急忙去检查防护墙。";
						sleep2 4000;
						npctalk "我们到底会变成怎么样呢…?";
						break;
					case 10:
						npctalk "我是桃萝西 佛罗伦丝。";
						sleep2 4000;
						npctalk "自从昨天事之后，大家开始把生活用品往更深处转移了。";
						sleep2 4000;
						npctalk "本来安全的安全室受到不明的污染。";
						sleep2 4000;
						npctalk "大家决定迁移至更安全的地方。";
						break;
					case 11:
						npctalk "我是桃萝西 佛罗伦丝，爆炸发生后第50天。";
						sleep2 4000;
						npctalk "Dr.普蕾莎和许多研究员经过长久的讨论后...";
						sleep2 4000;
						npctalk "决定钻开安全室的隔墙后转移到未受能量风暴波及的地上区域去。";
						sleep2 4000;
						npctalk "竟然要钻洞出去.. ! ";
						sleep2 4000;
						npctalk "还以为是永远出不去呢?";
						break;
					case 12:
						npctalk "我是桃萝西，这是最后一次录音。";
						sleep2 4000;
						npctalk "……我不想死，呜呜..";
						sleep2 4000;
						npctalk "我不想变成跟他们一样!!";
						sleep2 4000;
						npctalk "...我想活下去...";
						break;
					case 13:
						npctalk "我是宾珊特。";
						sleep2 4000;
						npctalk "哦~ 我现在所在位置是服务器室~";
						sleep2 4000;
						npctalk "我X...到处都是灰尘.... 啊! 忘了麦克风还开着呢...";
						sleep2 4000;
						npctalk "我来看看，要更换的是NANA公司11年生产的超贵的CPU。";
						sleep2 4000;
						npctalk "虽说曾是可买好几栋房子的贵重物品，但现如今却是我手中的玩物呢!";
						sleep2 4000;
						npctalk "现在要做的就是把旧的取出来，然后... 换上新的上去。";
						sleep2 4000;
						npctalk "完成了，很简单!";
						sleep2 4000;
						npctalk "希维亚你要不要吃炸鸡? 我这有香辣味的.. (吱吱.. 吱吱)";
						sleep2 4000;
						npctalk "??..??";
						break;
					case 14:
						npctalk "我是桃萝西 佛罗伦丝，负责清洗衣物的桃萝西。";
						sleep2 4000;
						npctalk "从今天开始, 我打算尽我所能记录下大家的声音。";
						sleep2 4000;
						npctalk "这地方有很多人，目前都还活着。";
						sleep2 4000;
						npctalk "希样能用这种方式留下他们的故事。";
						sleep2 4000;
						npctalk "也许以后会有人依靠这个记起我们。";
						sleep2 4000;
						npctalk "来.. 先采访谁好呢?";
						break;
					case 15:
						npctalk "你好! 我是艾依特，贝鲁兹城的助理工程师。";
						sleep2 4000;
						npctalk "哈哈.. 有点尴尬呢?";
						sleep2 4000;
						npctalk "前不久地堡里酿了葡萄酒。";
						sleep2 4000;
						npctalk "在地堡里生活久了难免对返回地面感到绝望.";
						sleep2 4000;
						npctalk "记得那次也没喝多少，隔壁的朋友就醉了。";
						sleep2 4000;
						npctalk "酒量那么差还敢跟我拼。";
						sleep2 4000;
						npctalk "我可是酒王呢! 哈哈!";
						sleep2 4000;
						npctalk "不过看着他让我想起我家小朋友。";
						sleep2 4000;
						npctalk "一头长发加上满脸的雀斑... ";
						sleep2 4000;
						npctalk "..艾依特! 帮我看看这个好吗?";
						sleep2 4000;
						npctalk "啊.. 抱歉! 我要去工作了，下次有机会再继续吧。";
						sleep2 4000;
						npctalk "呜! 那艾依特的采访就改到下次吧! 我是桃萝西!";
						break;
					case 16:
						npctalk "你好! 艾依特你有空吗?";
						sleep2 4000;
						npctalk "你好! 桃萝西. 还要继续上次的那个采访吗?";
						sleep2 4000;
						npctalk "好吧. 谁让我答应过你呢! 上次说到哪里了?";
						sleep2 4000;
						npctalk "那个满脸雀斑的长发小朋友!";
						sleep2 4000;
						npctalk "对! 那小朋友老爱缠着我呢。";
						sleep2 4000;
						npctalk "从小就这样.. 哈..";
						sleep2 4000;
						npctalk "来贝鲁兹城时还心想能摆脱他, 有点窃喜.";
						sleep2 4000;
						npctalk "没想到他竟然跟到实验洞来了, 他真的太厉害了!";
						sleep2 4000;
						npctalk "虽然他性格很率真...";
						sleep2 4000;
						npctalk "但是嘴倒是挺硬, 从来没说过喜欢我.";
						sleep2 4000;
						npctalk "不过他那点心思都在脸上写着呢!";
						sleep2 4000;
						npctalk "有本事别跟着我啊...哈哈哈!";
						sleep2 4000;
						npctalk "现在还真是特别想你啊~小朋友. ..呵呵!";
						sleep2 4000;
						npctalk ".....但你也在那天，那天....";
						sleep2 4000;
						npctalk ".................桃萝西. ..算了, 不说了。";
						break;
					case 17:
						npctalk "--------轰-----";
						sleep2 4000;
						npctalk "呜..";
						sleep2 4000;
						npctalk "呜呜呜呜...";
						sleep2 4000;
						npctalk "啊! 怎么会这样!!";
						sleep2 4000;
						npctalk "呜呜呜..";
						sleep2 4000;
						npctalk "-------轰轰-----";
						sleep2 4000;
						npctalk "--吱吱-啊 --他 --刚刚 --嗡嗡嗡-- 他嗡-找嗡--样..呢";
						sleep2 4000;
						npctalk "--嗡嗡嗡--道了。";
						sleep2 4000;
						npctalk "-喀嚓-";
						sleep2 4000;
						npctalk "博士看起来也很疲惫呢!";
						sleep2 4000;
						npctalk "哦! 这东西开着呢? 开太久会被骂喔..";
						sleep2 4000;
						npctalk "嗯! 我是巴尼 路易德，最近感到很累。";
						sleep2 4000;
						npctalk "只是状况紧急，大家情绪都不太好。";
						sleep2 4000;
						npctalk "呼...";
						sleep2 4000;
						npctalk "吱吱..";
						break;
					case 18:
						npctalk "我是桃萝西 佛罗伦丝，今天在监控室发现了一个记忆音盘。";
						sleep2 4000;
						npctalk "也许是实验当天的黑匣子~ 现在来播放!";
						sleep2 4000;
						npctalk "嗡嗡嗡-- 啊.. 一开始是杂音... 有声音了。";
						sleep2 4000;
						npctalk "祝好运..";
						sleep2 4000;
						npctalk "(女声) 啊.. 很遗憾没谈过恋爱。";
						sleep2 4000;
						npctalk "(其他女声) 啊.. 很可惜没有边吃边看这景况...嗡嗡嗡--";
						sleep2 4000;
						npctalk "哦? 没了吗? 这声音是送干洗衣物的尔特米额呢!";
						sleep2 4000;
						npctalk "..嗯..原来如此，那天结局是那样啊..... ";
						sleep2 4000;
						npctalk "达喀!";
						break;
				}
				sleep2 3000;
				$@lp01on = 0;
				next;
				mes "储存于记忆音盘的全部语音信息播放完毕。";
				erasequest 7652;
				erasequest 7655;
				setquest 7653;
				getexp 1500000,1000000;
				if (countitem(22691) < 1 && countitem(22692) < 1 && countitem(22693) < 1 && countitem(22694) < 1 && countitem(22695) < 1)
					getitem rand(22691,22695),1;
				next;
				specialeffect EF_SPELLBREAKER;
				mes "当试图取出记忆音盘时, 连接的部分又重新断开,整个记忆音盘又变成了碎片状";
				next;
				cutin "Arquien_n_atnad01", 2;
				mes "[奈伊]";
				mes "其实播放的内容只有一段, 但是每次播到一半就会变成碎片,";
				mes "看来是有人故意这么设计的,";
				mes "每次都要重新整理, 真麻烦..";
				next;
				mes "[奈伊]";
				mes "明明有很高的科技水平, 为什么要这样设计呢?";
				mes "而且其中还有重复的内容..";
				mes "我看一定是有人故意阻止别人去挖掘过去的事.";
				next;
				mes "[奈伊]";
				mes "这内容我会另行记录后交给父亲的，";
				mes "今天也辛苦你了。";
				close2;
			} else {
				mes "没有要播放的记忆音盘。";
				close2;
			}
		} else {
			cutin "Arquien_n_atnad01", 2;
			mes "[奈伊]";
			mes "喂! 请你不要乱碰好吗?";
			close2;
		}
	} else {
		mes "目前正在播放中。";
		close2;
	}
	cutin "",255;
	end;
OnInit:
	$@lp01on = 0;
	end;
}

**Comment by idamonli** [comment]
sleep2 3000;
$@lp01on = 0;
next;
mes "储存于记忆音盘的全部语音信息播放完毕。";
erasequest 7652;
erasequest 7655;
setquest 7653;
![45223750-b09d7280-b2ea-11e8-93f0-f0b9457abba9](https://user-images.githubusercontent.com/13962741/45528764-6a796f00-b814-11e8-9981-84f1d599276b.png)

**Comment by idamonli** [comment]
[调试]: npc_scriptcont: 音盘#e152a01 (sd->npc_id=110019671) is not 'Unknown NPC'
 (id=0).

**Comment by exneval** [comment]
Will test ur script

**Comment by idamonli** [comment]
Do you understand Chinese?

**Comment by exneval** [comment]
I don't but I can use machine translator to help me understand better

**Comment by idamonli** [comment]
Because we 've translated the English script into Chinese.

**Comment by exneval** [comment]
Is that rA ep.15 script?

**Comment by idamonli** [comment]
ep.16.1

**Comment by exneval** [comment]
@idamonli 

unfortunately i can't reproduce the issue with this script

`morocc,153,90,6	script	次元裂缝导览员#xxz	4_M_EIN_SOLDIER,{
	mes "准备播放记忆音盘的语音信息。";
	switch(rand(1,2)) {
	case 1:
		npctalk "今天是贝鲁兹城第4885次计划的最后一次实验日。";
		sleep2 4000;
		npctalk "大家都希望成功一起去实验洞参观了。";
		sleep2 4000;
		npctalk "刚好我是研究洞的值班人员，所以没参加。";
		sleep2 4000;
		npctalk "还有拓堤奥也不是主计划的成员，所以跟我一起守着研究洞。";
		sleep2 4000;
		npctalk "虽感到有点凄凉.... 但期待能成功..";
		sleep2 4000;
		npctalk "刚才没闪光吗? 喂!";
		sleep2 4000;
		npctalk "轰隆! 嗡嗡嗡...";
		break;
	case 2:
		npctalk "喀嚓-嗡嗡 不要拦我，哈哈，我要记录下来";
		sleep2 4000;
		npctalk "噗哈哈哈哈!";
		sleep2 4000;
		npctalk "我不是发疯，只是太好笑了，哈哈哈!";
		sleep2 4000;
		npctalk "现在是好笑的时候吗?";
		sleep2 4000;
		npctalk "当然不是，只是，呵呵呵....";
		sleep2 4000;
		npctalk "…那要哭吗? 嗯? 反而有希望不是吗?";
		sleep2 4000;
		npctalk "我们的希望啊!";
		sleep2 4000;
		npctalk "啪-! 啊… 这.. 这一击是杰雷特…..";
		sleep2 4000;
		npctalk "唉! 你欠揍喔!";
		sleep2 4000;
		npctalk "哦? 是在录音吗?";
		break;
	}
	sleep2 3000;
	next;
	mes "储存于记忆音盘的全部语音信息播放完毕。";
	next;
	specialeffect EF_SPELLBREAKER;
	mes "当试图取出记忆音盘时, 连接的部分又重新断开,整个记忆音盘又变成了碎片状";
	close;
}`

**Comment by exneval** [comment]
@idamonli if no more follow up, I'll close this issue

**Comment by exneval** [comment]
@idamonli OK I'll close this and set as Invalid
