### ISSUE TITLE
[CentOS] Compile warning

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#463]
![image](https://user-images.githubusercontent.com/4651777/45225927-3f60be00-b2f0-11e8-81da-987137974b7b.png)

**Comment by exneval** [comment]
Thanks will check it

**Comment by exneval** [comment]
@Miraakol can you check your centos gcc version?

**Comment by Miraakol** [comment]
im sorry but don't know how to check it. can you teach me?

**Comment by exneval** [comment]
type
gcc --version

**Comment by Miraakol** [comment]
where? root or trunk folder?

**Comment by Miraakol** [comment]
![image](https://user-images.githubusercontent.com/4651777/45255365-1146b100-b3b8-11e8-9676-310b35f31013.png)

**Comment by exneval** [comment]
thank you

**Comment by exneval** [comment]
Since you are using old version of gcc compiler, it's not really a problem..
so you can ignore it.

**Comment by exneval** [comment]
You need to upgrade the OS version so it has default higher gcc version
