### ISSUE TITLE
[Windows] Server issues

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#465]
So far, we don't know what caused the problem.

Server is running after some time, the player can't log in the map server.
Players playing games are out of touch with the map server.
The player can login to the character interface, but can not enter the game.
The map server does not have any hints.

**Comment by exneval** [comment]
If player can login to the char selection but can't enter the game that means the map server is down, are you using gdb when starting the server?

**Comment by exneval** [comment]
ah yes.. i ask him to move to a better platform...
can you do the same?
add my discord exneval#5925
let's talk in there more details

**Comment by idamonli** [comment]
exneval#5925？
where？

**Comment by exneval** [comment]
do you have discord account?

**Comment by idamonli** [comment]
It is very difficult for me to use this software.

**Comment by exneval** [comment]
ok, let's do this here...
do you have gdb installed in your vps?

**Comment by idamonli** [comment]
I'm really working on the deployment.

**Comment by idamonli** [comment]
This BUG appeared, but it was still unable to obtain a valid record.

**Comment by idamonli** [comment]
My friend seems to have told you this before.

**Comment by exneval** [comment]
are the server using windows or linux?

**Comment by idamonli** [comment]
My friend seems to have told you this before.

**Comment by idamonli** [comment]
windows

**Comment by exneval** [comment]
then are you compiling the server in debug mode?

it will help to tell where's the problem

**Comment by exneval** [comment]
whatis the version of your visual studio?

**Comment by idamonli** [comment]
VS2010

**Comment by exneval** [comment]
then are you compiling the server in debug mode?

it will help to tell where's the problem

**Comment by idamonli** [comment]
It's the debug mode.

**Comment by exneval** [comment]
when the problem happened again, screen shot it and send to me
you can send it to my e-mail ( exneval.rayz@gmail.com )

**Comment by idamonli** [comment]
If this problem comes up again, I 'll take a screenshot.

**Comment by exneval** [comment]
how often the problem occur?

**Comment by idamonli** [comment]
1 days  or  2 days

**Comment by exneval** [comment]
e-mail me the server website, so I can register and  join the server, live to watch it
