### ISSUE TITLE
When does sleep3 join?

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#467]
Sleep2 will agree that players can't move.

**Comment by exneval** [comment]
will implement sleep3 today, please wait for it

**Comment by Miraakol** [comment]
Thank you sir ex!

**Comment by exneval** [comment]
sleep2 5000,1;
will behave like old behavior so it can comaptible with custom rA script

**Comment by Miraakol** [comment]
sleep2 1000 + .Rest * 60000;

Stolao's daily reward player cant move.

**Comment by exneval** [comment]
@Miraakol please test the sleep2 with parameter

`sleep2 1000 + .Rest * 60000,1;`

**Comment by Miraakol** [comment]
Thanks for the new update! Still at work will test it later.

**Comment by Miraakol** [comment]
done testing, works perfectly! @exneval thanks sir ex!

**Comment by idamonli** [comment]
This is great!
