### ISSUE TITLE
OnPCStatCalcEvent: problem~

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#469]
Sometimes it fails.
for example:
attachrid.
click onsome NPC.

**Comment by exneval** [comment]
will test it

**Comment by exneval** [comment]
@idamonli  can you give me some script details?

**Comment by idamonli** [comment]
prontera.gat,138,94,5	script	安全精练人员	878,{

	specialeffect2 EF_HEAL2;
	percentheal 100,100;
	sc_end SC_BLESSING;
	specialeffect2 EF_BLESSING; sc_start SC_BLESSING,600000,10;
	sc_end SC_INCREASEAGI;
	specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,600000,10;

	mes " [xxxxx] ";
	mes " xxxx";
	mes " xxxxxxxxxxxxxx";
	mes " xxxxxxxxxxxxxxxxxxx";
	next;
..............................................................


	-	script	NPCStat	-1,{
end;
	OnPCStatCalcEvent:
if(BaseLevel<50)
end;


bonus bMaxHP,1000;	
bonus2 bAddRace,RC_All,100; //               
bonus2 bMagicAddRace,RC_All,100; //      
bonus bAspd,3;//
bonus bAspdRate,30;//  


		end;
	}

**Comment by idamonli** [comment]
![gds0w8lwg_z8cgt9h vj v4](https://user-images.githubusercontent.com/13962741/45581338-c0aae880-b8ce-11e8-8dcc-1c86415b8562.png)
![h07l mcy yto8 6h x um2q](https://user-images.githubusercontent.com/13962741/45581339-c1437f00-b8ce-11e8-9c03-2ae5cf08fc94.png)

**Comment by idamonli** [comment]
From the picture, the reward in the event failed.

Before clicking on NPC： MHP： 16707
After clicking on the NPC ：MHP： 15707

**Comment by idamonli** [comment]
The event should ignore whether the player has an NPC connection.
