### ISSUE TITLE
2017-01-25ragexere

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#474]
when clicking rodex client closes. im using nemo secretdataz for diffing, zackdreaver's data, and fully patched kro. what possible problem?

**Comment by exneval** [comment]
there's a problem with your texture data of RODEX, because kRO change the texture for 3 times
try higher clientdate May 2017 , if still crashed, you need to update it

**Comment by Miraakol** [comment]
But there is no prompting that there's error or missing textures.

**Comment by Miraakol** [comment]
i guess it is the client itself has a problem. because some of the client have i tried is working properly with rodex.

**Comment by Miraakol** [comment]
already tested that yes it works fine, but i dont like the UI the new icons (alt+v) i want the old one but supports new ui for rodex.

**Comment by Miraakol** [comment]
actually i can use older client and older rodex but the included textures in zackdreaver's data folder is not translated. so i plan to translate it manually using photshop cause text are not in msgstring it is bounded on the texture itself.
