### ISSUE TITLE
NEW refine UI is achieve？？？

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#481]
![6ee7f18c8e2442e2a4e5d7116764da55](https://user-images.githubusercontent.com/13962741/45629112-36c66f80-bac8-11e8-8471-1c0f5409ec75.jpg)
![4929f366a2b8422f83273422123cc499](https://user-images.githubusercontent.com/13962741/45629115-36c66f80-bac8-11e8-8e1a-566acf594bfa.jpg)
![a6be1157ed334111936dc2c01cb15854](https://user-images.githubusercontent.com/13962741/45629116-375f0600-bac8-11e8-9391-ce238b93a599.jpg)
![a64c344c61f54b75af4dc2e7e211f6c3](https://user-images.githubusercontent.com/13962741/45629117-375f0600-bac8-11e8-9888-ad93267f426c.jpg)

**Comment by exneval** [comment]
Still working on it, please wait

**Comment by exneval** [comment]
@idamonli 
![screenidathena001](https://user-images.githubusercontent.com/3431785/45672379-2d81e500-bb52-11e8-83e9-58f108a77075.jpg)

will commit soon

**Comment by Miraakol** [comment]
Just wanted to ask what langtype are you using and what client date?

**Comment by exneval** [comment]
2018-06-20eRagexeRE

```
<servicetype>korea</servicetype>
<servertype>sakray</servertype>
<langtype>0</langtype>
```

**Comment by Miraakol** [comment]
@exneval thanks by the way, do yo have any idea what client date new UI of rodex started?

**Comment by exneval** [comment]
@Miraakol kRO changed UI ROdex 3times as far as I remembered and the last one was in 2017 client, maybe on May or June

**Comment by Miraakol** [comment]
@exneval thanks for that information

**Comment by exneval** [comment]
@Miraakol  why not trying 2018 client? You can help idA to even become better by using default clientdate that idA already set

**Comment by exneval** [comment]
@idamonli @Miraakol for now RefineUI system can be used only from atcommand '@refineui' and script command 'open_refineui'

will update for the NPC interaction in the future

**Comment by Miraakol** [comment]
@exneval do you think using latest client is good for official use?

**Comment by Miraakol** [comment]
@exneval btw thanks for the new refine system i will test it later

**Comment by exneval** [comment]
@Miraakol 2018-06-20eRagexeRE is stable

**Comment by Miraakol** [comment]
alright will test newer client this coming weekend. what will i use as a main data client side? zack or asheraf?

**Comment by exneval** [comment]
@Miraakol 
use zack as main data
and asheraf for fixing errors

**Comment by Miraakol** [comment]
so you are saying zackdreaver's is more updated than asheraf's? how about system folder? and what nemo patcher will i use? secrert or 4144?

**Comment by exneval** [comment]
once again I'll say, I use zack as main translation then if errors found, I fixed them with Asheraf

for nemo use 4144 only

**Comment by exneval** [comment]
@Miraakol 
Update: How to use langtype 1 in 2018 client
1. Edit sclientinfo.xml <servicetype>korea</servicetype> to <servicetype>america</servicetype>
2. Keep the <servertype>sakray</servertype>
3. Edit <langtype>0</langtype> to <langtype>1</langtype>
4. In your luafiles514/lua files/ folder there is a folder called "service_korea" and within it there're files called "ExternalSettings_KR" and "externalsettings_kr_sak"; Rename the folder to "service_usa" and the files to "externalsettings_usa﻿"﻿ and "externalsettings_usa_sak"

Hope you'll able to do it
