### ISSUE TITLE
[Instance] Nightmarish Jitterbug

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#482]
![qq 20180919145054](https://user-images.githubusercontent.com/13962741/45735653-34c0f580-bc1b-11e8-8a48-e09ae0968228.jpg)

.@menu = select("Talk:Hurry");

CLICK    Hurry

PLAYER~
 Has been associated with NPC status and cannot be moved.

**Comment by idamonli** [comment]
For the first time in the maze don't seem to be a problem. Only when the game again chance there will be a problem

**Comment by exneval** [comment]
let me try to run the instance once again

**Comment by exneval** [comment]
@idamonli I was tested the instance 2 times in 2 days. The option Hurry was working fine in idAthena, so I'm unable to reproduce the issue, please check your script modification, thanks
