### ISSUE TITLE
2018 client

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#484]
![image](https://user-images.githubusercontent.com/4651777/45816871-82b72580-bd0f-11e8-9868-69cfd753cf55.png)

how to fix this?

**Comment by Miraakol** [comment]
im using zackdreaver's data folder and system folder

**Comment by Miraakol** [comment]
fixed replacing skillinfoz from asheraf's data

**Comment by exneval** [comment]
That's why I said before used Asheraf for fixing errors

**Comment by Miraakol** [comment]
why ignition break has no effect?

**Comment by exneval** [comment]
The fix will come in the next update

**Comment by Miraakol** [comment]
![image](https://user-images.githubusercontent.com/4651777/45819949-37554500-bd18-11e8-8724-6b935d07c8ef.png)
new warning is this ok?

**Comment by exneval** [comment]
@Miraakol it's fine, will also fix it along with the animation issue

**Comment by Miraakol** [comment]
thanks @exneval also why i cant refine?
![image](https://user-images.githubusercontent.com/4651777/45820291-088b9e80-bd19-11e8-9bdc-35d8add3ccf0.png)

**Comment by exneval** [comment]
@Miraakol select the material first

**Comment by Miraakol** [comment]
@exneval many thanks to you! because my hosting dont offer upgrading of OS

**Comment by Miraakol** [comment]
@exneval do you have any idea how to restore the font style and font size? because font size are too small.

**Comment by exneval** [comment]
use another langtype maybe langtype 1, but it needs some tweaks

**Comment by Miraakol** [comment]
@exneval also what episode are we?

**Comment by exneval** [comment]
@Miraakol 14.2 with Some parts of Hero Trails Episode
