### ISSUE TITLE
[Stylist UI] Second Costume

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#485]
![qq 20180920222425](https://user-images.githubusercontent.com/13962741/45825300-85704580-bd24-11e8-90ff-70e97456f053.png)
Can not click

**Comment by idamonli** [comment]
Oh, sorry. I found it.
20180718~exe
I'm not ready for this.

**Comment by exneval** [comment]
@idamonli  need to support 2017 July clients first

**Comment by exneval** [comment]
f4b4955 should support July Ragexe Client

**Comment by exneval** [comment]
@idamonli the fix will come soon
