### ISSUE TITLE
rAthena emotion 

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#486]
The instructions have been updated
 rathena : 
/**
 * Shows an emotion on top of a NPC by default or the given GID
 * emotion <emotion ID>{,<target ID>};
 */

idathena: 
/*==========================================
 *	Shows an emoticon on top of the player/npc
 *	emotion emotion#, <target: 0 - NPC, 1 - PC>, <NPC/PC name>
 *------------------------------------------*/

**Comment by exneval** [comment]
will change the format, but for the emote constant will stay as it is for now

**Comment by exneval** [comment]
NOTE: rA emotion constants still not supported, please use default constants
