### ISSUE TITLE
Picky Peck issue

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#489]
![image](https://user-images.githubusercontent.com/4651777/45882782-c5493280-bde1-11e8-9a2d-0081ee3e8fe1.png)

**Comment by Miraakol** [comment]
![image](https://user-images.githubusercontent.com/4651777/45882804-dc882000-bde1-11e8-9f72-95b766268fb5.png)

**Comment by Miraakol** [comment]
how did i reproduce that? i was on the guild castle mid prontera and attacked the monsters using doram skill then suddenly got that errors.

**Comment by exneval** [comment]
will check it

**Comment by exneval** [comment]
@Miraakol  can't reproduce it, did you modify the src ?

**Comment by exneval** [comment]
@Miraakol i'm able to reproduce it

**Comment by Miraakol** [comment]
im using clean src

**Comment by Miraakol** [comment]
try spam the skills?

**Comment by Miraakol** [comment]
wait ill try to reset server

**Comment by Miraakol** [comment]
try to spam the skill

**Comment by Miraakol** [comment]
![image](https://user-images.githubusercontent.com/4651777/45885830-12c99d80-bdea-11e8-8cbc-c8b62116a27c.png)

**Comment by Miraakol** [comment]
i tried to spam skill to barricade

**Comment by exneval** [comment]
will fix in next commit

**Comment by Miraakol** [comment]
thanks @exneval also glad you are really active this past few days! keep it up!

**Comment by exneval** [comment]
@Miraakol thank you, to be honest, I'll be inactive again for a time being.. that's why I pushed everthing that I can... sorry

**Comment by exneval** [comment]
Should fix at df47b25
