### ISSUE TITLE
Character landing anomaly

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#491]
![screen 006](https://user-images.githubusercontent.com/13962741/45911947-a92eab00-be4c-11e8-90ba-4f5b2d3330f6.jpg)
After a MAP crash, the character landed with an exception. Although it entered the game, it could not move and could not display the NPC.
The others can still land.
Do you know how to solve this problem?

**Comment by idamonli** [comment]
These problems are now found in other accounts.
It seems to be an update.

**Comment by exneval** [comment]
@idamonli  which update?
tell me how to reproduce it then I'll try it asap...

**Comment by idamonli** [comment]
It was my synchronization that caused you trouble.

**Comment by exneval** [comment]
related to #492
