### ISSUE TITLE
[Attendance System] Map server crashed

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#492]
![image](https://user-images.githubusercontent.com/4651777/45914611-d776af80-be79-11e8-84a1-2feecea8831d.png)

**Comment by exneval** [comment]
@Miraakol never experience what like the title said.. please use gdb debugger...

I always dual client and working fine

**Comment by Miraakol** [comment]
did you bypass packet encryption?

**Comment by Miraakol** [comment]
also i dont have any idea how to run gdb debugger

**Comment by Miraakol** [comment]
will try a clean installation.

**Comment by Miraakol** [comment]
still map crash

**Comment by Miraakol** [comment]
![image](https://user-images.githubusercontent.com/4651777/45915636-cb471e00-be8a-11e8-9346-cf90e2c4b430.png)

**Comment by Miraakol** [comment]
it happens when you set the wrong dates in attendance db.

**Comment by exneval** [comment]
@Miraakol thank you for the gdb, I'll test it
