### ISSUE TITLE
Random Properties~~~~

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#494]
![qq 20180922204811](https://user-images.githubusercontent.com/13962741/45917406-05271d00-bea9-11e8-906a-27a06595520d.png)
A random property of a weapon if attribute is given.
It overrides the attributes of arrows.

such as：
There's an Earth Element on the weapon.
At the same time equipped with water Element arrows。

Weapon attack Element is Earth Element。

**Comment by exneval** [comment]
Will test it

**Comment by exneval** [comment]
faa769f should fix the issue
