### ISSUE TITLE
Some mobs act weird.

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#497]
![screen 009](https://user-images.githubusercontent.com/13962741/45929512-8227c480-bf85-11e8-97a5-72880da192b0.jpg)
![screen 010](https://user-images.githubusercontent.com/13962741/45929513-82c05b00-bf85-11e8-98cc-621ea0a87e92.jpg)
![screen 011](https://user-images.githubusercontent.com/13962741/45929514-82c05b00-bf85-11e8-88d8-a94f16b4ccb3.jpg)
![screen 012](https://user-images.githubusercontent.com/13962741/45929515-82c05b00-bf85-11e8-8c37-9bef596c3cc2.jpg)
Some monsters look like this.
No walking.
Coming straight at you from a long distance.
No walking process。

MOB->2949

**Comment by exneval** [comment]
will test it
