### ISSUE TITLE
waitingroom BUG

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#514]
It is not possible to determine whether the client has a problem or whether the source packet has a problem
![qq 20181003212215](https://user-images.githubusercontent.com/13962741/46413310-329a8300-c753-11e8-9275-803a9924afc1.jpg)

**Comment by idamonli** [comment]
The last character becomes a question mark.
English or symbol ~ not directly displayed。

**Comment by idamonli** [comment]
this is 20180307
![qq 20181003213202](https://user-images.githubusercontent.com/13962741/46413635-fd426500-c753-11e8-9c5e-04ef100b0593.jpg)

**Comment by exneval** [comment]
will test it

**Comment by idamonli** [comment]
waitingroom "休息室*",20,"文强 派内迪特#knt::OnStartArena",1;
Add a punctuation or letter at the end to make the display normal
How to add this punctuation or letter to the source code?

**Comment by exneval** [comment]
I understand, thank you for the information,
will test it as soon as possible
