### ISSUE TITLE
@whodorps~~~BUG?

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#520]
![qq 20181029212933](https://user-images.githubusercontent.com/13962741/47652899-2c68bc80-dbc2-11e8-986d-f80a6684d4b7.png)
Unable to query information

**Comment by exneval** [comment]
How to reproduce? 
Can you test with clean idA?

**Comment by idamonli** [comment]
@whodorps 526
@whodorps 1105
。。。。。
Is that right?

**Comment by idamonli** [comment]
I found it.

@reloaditemdb
@reloadmobdb

It appears to have been caused by the use of these two instructions.

**Comment by exneval** [comment]
Will check it

**Comment by exneval** [comment]
Should be fixed by d338158
