### ISSUE TITLE
Sorcere summon Elemental

### ISSUE THREAD

**Issue by poporing** [idathena/trunk#521]
Hi,
I found this and as I read in your code it's not implemented:
https://github.com/RagEmu/Renewal/commit/37f1da997c0c3b683d7fcc2eee9b8a6c8245de87

This is the official formula for sorcerer summon elemental

**Comment by exneval** [comment]
I've been looking for that code for a long time.
Will try to implement it.

**Comment by poporing** [comment]
Project dead? Hope not =)

**Comment by exneval** [comment]
@poporing  course not, will be back soooooon.

**Comment by poporing** [comment]
Hope a gift for christmas xD
Good news @exneval
