### ISSUE TITLE
2564-Fenrir Use the Skill MAP server to crash.

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#523]
2564,Fenrir@WL_COMET,attack,2213,5,2000,5000,30000,no,around6,always,,,,,,,,
2564,Fenrir@WL_TETRAVORTEX,attack,2217,5,1000,5000,30000,no,target,always,0,,,,,,,
2564,Fenrir@WL_EARTHSTRAIN,attack,2216,5,3000,3000,30000,no,around6,always,0,,,,,,,
2564,Fenrir@NPC_SHIELDBRAKE,attack,346,10,3000,1000,10000,no,target,always,0,,,,,,,

It must have been WL_COMET.

**Comment by idamonli** [comment]
case WL_COMET:
				i = (c > 1 ? rnd()%c : 0);
				if (c && (tsd = map_id2sd(p_sd[i])))
					status_charge(&tsd->bl, 0, skill_get_sp(skill_id, *skill_lv) / 2);
				break;

**Comment by exneval** [comment]
please change that Fenrir WL_COMET to 

`2564,Fenrir@NPC_COMET,attack,708,5,2000,5000,30000,no,target,always,,,,,,,,`
