### ISSUE TITLE
request> add 2015-11-04a client

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#55]
- 2015-10-29a Download (Main Server) (Warning found issues random unknown packets)

source: rathena

sir @exneval can you addd this client to idathena because rathena posted that -2015-10-29a has a packet issues that has not been resolved. thank you in advance! :)

link: https://rathena.org/board/topic/104205-2015-client-support/

**Comment by exneval** [comment]
Well I don't haven't experienced any issues like that. Have you?
