### ISSUE TITLE
[Crash] Map-server

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#554]
read~~~~mob_db.conf

2019.06.25 Download source code, compiled and run

**Comment by idamonli** [comment]
#ifdef RENEWAL
unsigned short status_calc_ematk(struct block_list *bl, struct status_change *sc, int matk, bool viewable)
{
	if(!sc || !sc->count)
		return (unsigned short)cap_value(matk,0,USHRT_MAX);

	if(viewable) {
		if(sc->data[SC_CHATTERING])
			matk += sc->data[SC_CHATTERING]->val2;
		return (unsigned short)cap_value(matk,0,USHRT_MAX);
	}

	**if(sc->data[SC_MATKFOOD])
		matk += sc->data[SC_MATKFOOD]->val1;**
vs2013 track this~~~~~~

**Comment by exneval** [comment]
@idamonli Hash git version?

the issue should be fine with this commit c9e8b84
