### ISSUE TITLE
[Support] convert_mobdb.pl

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#556]
Can you get this file to support Chinese?

<kROName>
<iROName>

**Comment by idamonli** [comment]
kROName 
iROName

**Comment by exneval** [comment]
@idamonli can you give me an example of the entry in mob_db.txt?

**Comment by exneval** [comment]
@idamonli do you have discord?

**Comment by idamonli** [comment]
1001,SCORPION,蝎子,Scorpion,16,153,1,108,81,1,33,7,16,5,12,15,10,5,19,5,10,12,0,4,23,0x2003091,200,1564,864,576,0,0,0,0,0,0,0,990,70,904,5500,757,57,943,210,7041,100,508,200,625,20,0,0,0,0,4068,1

**Comment by idamonli** [comment]
2890,C4_ARGOS,[狂怒]艾斯蜘蛛,Furious Argos,47,5025,1,900,3030,1,114,45,58,8,38,22,25,5,26,15,10,12,2,4,25,0x2003095,300,1468,468,768,0,0,0,0,0,0,0,1025,9000,911,1200,1042,500,757,61,511,670,601,250,10017,15,0,0,0,0,4075,1

**Comment by idamonli** [comment]
[mob_db.txt](https://github.com/idathena/trunk/files/3341331/mob_db.txt)
this is my mob_db.txt

**Comment by exneval** [comment]
@idamonli will try it

**Comment by exneval** [comment]
@idamonli it is in ANSI encoding right?

**Comment by idamonli** [comment]
@exneval thanks

**Comment by idamonli** [comment]
it is ANSI

**Comment by exneval** [comment]
[Uploading mob_db.zip…](mob_db.conf)
please try this

**Comment by idamonli** [comment]
Just now, I tried to improve your file.
[convert_mobdb.zip](https://github.com/idathena/trunk/files/3341364/convert_mobdb.zip)

**Comment by exneval** [comment]
@idamonli yea I did the same thing, will update it in the next commit

**Comment by exneval** [comment]
@idamonli but your mob_db.txt has invalid character in drop table, search for character "?"

**Comment by exneval** [comment]
@idamonli 2996,XM_CELINE_KIMI has invalid character ?

**Comment by idamonli** [comment]
@exneval Where is it?

**Comment by exneval** [comment]
@idamonli in your mob_db.txt find character question mark "?", it is in celine kimi 2996

**Comment by idamonli** [comment]
{
	Id: 2996
	SpriteName: "XM_CELINE_KIMI"
	Name: "席琳基米"
	Level: 160
	HP: 66666700
	SP: 1
	EXP: 4444440
	JEXP: 3666670
	Range1: 2
	ATK1: 6666
	ATK2: 6666
	DEF: 479
	MDEF: 444
	Stats: {
		STR: 144
		AGI: 166
		VIT: 44
		INT: 444
		DEX: 166
		LUK: 166
	}
	Range2: 10
	Range3: 12
	Size: "Size_Large"
	Race: "RC_Undead"
	Element: {
		Type: "Ele_Ghost"
		Level: 1
	}
	Mode: "0x6283695"
	Speed: 100
	aDelay: 768
	aMotion: 1056
	dMotion: 480
	MEXP: 2020200
	MVPDrops: (
	{
		ItemId: 12246
		Rate: 2500
	}
	)
	Drops: (
	{
		ItemId: 712
		Rate: 10000
	},
	{
		ItemId: 7640
		Rate: 4000
	},
	{
		ItemId: 7642
		Rate: 4000
	},
	{
		ItemId: 13442
		Rate: 100
	},
	{
		ItemId: 19701
		Rate: 100
	},
	{
		ItemId: 22534
		Rate: 4000
	},
		Rate: 200
	{
		ItemId: 31023
		Rate: 1
		StealProtected: true
	}
	)
},
{
	Id: 2997
	SpriteName: "G_XM_CELINE_KIMI"
	Name: "席琳基米"
	Level: 160
	HP: 66666700
	SP: 1
	EXP: 0
	JEXP: 0
	Range1: 2
	ATK1: 6666
	ATK2: 6666
	DEF: 479
	MDEF: 444
	Stats: {
		STR: 144
		AGI: 166
		VIT: 44
		INT: 444
		DEX: 166
		LUK: 166
	}
	Range2: 10
	Range3: 12
	Size: "Size_Large"
	Race: "RC_Undead"
	Element: {
		Type: "Ele_Ghost"
		Level: 1
	}
	Mode: "0x6203695"
	Speed: 100
	aDelay: 768
	aMotion: 1056
	dMotion: 480
	Drops: (
	{
		ItemId: 6683
		Rate: 10000
	}
	)
},

It looks normal to me.

**Comment by exneval** [comment]
@idamonli see your 2996 doesn't have 28513 dropid

**Comment by idamonli** [comment]
@exneval Yeah, I saw it.Thank you very much.

**Comment by exneval** [comment]
`{
ItemId: 22534
Rate: 4000
},
Rate: 200
{`

this is not correct

**Comment by idamonli** [comment]
DamageTaken
It might be easier to create a new file for this project.

**Comment by exneval** [comment]
@idamonli well.. it already been added to the mob_db.conf just like random option group

**Comment by idamonli** [comment]
@exneval Yeah, okay. I'm trying to use the new structure.

**Comment by exneval** [comment]
@idamonli you can contact me faster in discord exneval#5925
