### ISSUE TITLE
[Error] Uninitialized variable as_skill_id

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#557]
![QQ图片20190630121055](https://user-images.githubusercontent.com/13962741/60392165-3d424700-9b30-11e9-8354-e8301e702551.png)
![QQ图片20190630121050](https://user-images.githubusercontent.com/13962741/60392166-3d424700-9b30-11e9-8a70-4076e684e66c.png)
Here are my modifications.
![QQ图片20190630121242](https://user-images.githubusercontent.com/13962741/60392187-737fc680-9b30-11e9-9d70-a31b71e9343f.png)

**Comment by exneval** [comment]
@idamonli thanks, will update in the next update
