### ISSUE TITLE
[Crash] Map server @mobinfo

### ISSUE THREAD

**Issue by idamonli** [idathena/trunk#560]
Use the GM command @mobinfo to crash~~

**Comment by exneval** [comment]
Any crash log? I can't reproduce it

**Comment by idamonli** [comment]
![QQ图片20190701205800](https://user-images.githubusercontent.com/13962741/60438327-03159a00-9c43-11e9-90b9-362694be4664.png)

**Comment by idamonli** [comment]
I just downloaded IDATHENA from GITHUB, not modified,

**Comment by idamonli** [comment]
I found it! It's caused by map_msg.conf.
It's my fault. I'm sorry.

**Comment by exneval** [comment]
@idamonli no problem, it's ok
