### ISSUE TITLE
[Request] Msg Conf

### ISSUE THREAD

**Issue by Miraakol** [idathena/trunk#566]
English translation of msg conf please :)

**Comment by GuillerMoDan** [comment]
Spanish translation of msg conf please ;)

**Comment by exneval** [comment]
@GuillerMoDan I'll do my best

**Comment by exneval** [comment]
@Miraakol English support in #569

**Comment by exneval** [comment]
@GuillerMoDan I'm having a hard time translating to Spanish, it will be really great if you can contribute on translating, please use the English translation in the pull request and compare it to the rA Spanish translation (as base), and create new translation for idAthena (Spanish)

**Comment by exneval** [comment]
This is the difference number between idA and rA msg_conf translation

- 172
- 213
- 215 - 226
- 234
- 236
- 284 - 285
- 379 - 381
- 389
- 407
- 451
- 500
- 517 - 534
- 543 - 547
- 669
- 699
- 717
- 720 - 774
- 924 - 927
- 1024
- 1053 - 1058
- 1178
- 1239 - 1249
- 1263
- 1295 - 1296
- 1376
- 1477
- 1479 - 1489
- 1490 - 1508

**Comment by GuillerMoDan** [comment]
ok, I'll compare it as soon as I can, thank you very much
