### ISSUE TITLE
[Question] What is idAthena?

### ISSUE THREAD

**Issue by zackdreaver** [idathena/trunk#61]
First, apologies if I have to put these questions in issue section.

So, i've seen this project since around 2012 or so, but I don't know the purpose of this emu?
Like, what you guys trying to emulate/follow:
- kRo/idRo mechanic?
- NPC with bahasa instead english?

this emu has "id" name but follow kRo mechanic and use english ?

and, btw how many people that work in this emu?

(Pake bahasa indonesia aja kali ya ngomongnya?)

**Comment by ernestfegarido** [comment]
i think this emulator uses rathena as their main src then merge other emulator like herc, 3ceam, rathena, brathena, and other ragnarok emulator :)

**Comment by exneval** [comment]
thanks @ernestfegarido for helping to answer the question.

@zackdreaver tidak apa apa kok gan, idAthena kan ga punya board, so it's fine to post it here, :smile:. Jika agan tanya buat apa sih idAthena ini? Saya akan coba jawab dengan tujuan idAthena pertama kali dibuat, idAthena sudah ada sebelum rAthena dibentuk, para devs. ya adalah member eA yang bermaksud untuk membuat emulator yang berbahasa Indonesia agar serupa dengan idRO, berhubung idAthena mengalami permasalahan pada hosting project saat itu, akhirnya idAthena pun tidak dilanjutkan kembali dan ditinggalkan. Beberapa tahun kemudian setelah dikenalnya emulator renewal terbaru rAthena, salah seorang pendiri idAthena terdahulu ingin mencoba menghidupkan kembali idAthena, sehingga dibentuk lah idAthena yang sekarang dengan base project menggunakan rAthena yang dikerjakan oleh beberapa developer Indonesia (sebelum saya). Tujuan nya masih sama, ya itu ingin menerjemahkan seluruh script ke Bahasa sehingga dapat seperti idRO, untuk 'mechanism' nya sendiri, idAthena saat itu hanya berpacu kepada update-an rAthena. Kemudian bergabung lah saya sebagai salah satu developer idA, pada saat itu, saya yang masih belum paham benar dengan percodingan C++, hanya bertugas sebagai merger code dari beberapa emulator (3ceam, rA, bRA), Kemudian bertahun-tahun hanya sebagai merger code, akhirnya saya mulai paham mengenai structure code yang dimiliki, dan saya memulai melakukan update sesuai dengan informasi yang ditemukan dari kRO updates. Tetapi ya memang nasib idA yang tidak baik, tak banyak server owner yang berasal dari Indonesia memakai emulator ini, padahal sudah banyak terjemahan yang dilakukan. Dan satu persatu developer pun meninggalkan project ini, dan hanya tinggal saya yang tersisa (banyak orang berkata bahwa idAthena seperti 3ceAM yakni one man project). Bukan tidak ada developer yang ingin bergabung, ada tentunya. Developer ternama rA yang berasal dari Indonesia sendiri, pernah mencoba mengupdate idAthena di gitHub, tetapi karena saya belum mengerti kenyamanan memakai git dalam project, saya tetap bertahan dengan google project, dan bekerja sendiri. Well, saya tahu itu sangat disayangkan, tetapi semua sudah berlalu.

Mengapa idAthena yang jelas jelas "ID" menggunakan english sebagai bahasa komunikasinya? Saya akan coba klarifikasi. idAthena yang sekarang ini, emulator yang mungkin seharusnya sudah menjadi 'dead project', justru digunakan oleh server owner yang berasal dari luar Indonesia, bahkan tak satupun server owner Indonesia mencoba memakai idAthena. Server owner inter ini lah yang membuat saya tetap mengupdate idAthena sampai sekarang (server nya yang sudah bertahan selama 3 tahun menggunakan idAthena). Jadi tak menutup kemungkinan pabila sever tersebut sudah closed, idAthena juga akan closed karena sudah tak ada lagi yang memakainya.

Jadi mungkin itulah, sebahagian yang bisa saya ceritakan mengenai idAthena.
Thanks agan @zackdreaver yang sudah berkenan ingin menanyakan eksistensi idAthena.

**Comment by zackdreaver** [comment]
Terima kasih atas penjelasannya,
agak disayangkan kalo ni emu bertahan dan harus menggunakan english hanya dikarenakan ada server luar yang make, bukannya server dari indo sendiri.

Kalau banyak server indo yang make ni emu, gw jujur ada ketertarikan buat bantu translate.

**Comment by exneval** [comment]
Mungkin di waktu mendatang, idA bisa promo lebih ke penyendia jasa ro Indonesia

**Comment by drsmile99** [comment]
kalau saya mau minta idA untuk di jadikan server offline bisag kakak. pengen punya offline server ro yg berbahasa indonesia. dan kalau boleh saya harus download dimana?

**Comment by drsmile99** [comment]
kak  trunk dan translatan npc yg kakak buat saya compile sama 3ceam offline untuk saya buat versi offlinenya semua npc dan warp masuk g berfungsi kira2 kaka da solusinya g makasih
