### ISSUE TITLE
item db script

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#92]
i tried this script:

7176,100_Cash,100 Cash,2,2,,10,,,,,0xFFFFFFFF,7,2,,,,,,{set #CASHPOINTS, #CASHPOINTS+100; dispbottom "You have received 100 Cash Points.";},{},{}

its not working i dont know why. the last time i used this script its working fine. can you check the src sir thanks in advance! :) @nanakiwurtz @exneval @cydh @jetkappu

**Comment by ernestfegarido** [comment]
i think set #CASHPOINTS, #CASHPOINTS IS NOT WORKING :( @nanakiwurtz @exneval @cydh @jetkappu

**Comment by exneval** [comment]
Can't reproduce this issue in latest git, maybe it already been fixed
