### ISSUE TITLE
this script

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#94]
i dont know why this script crashes the client :(
https://github.com/3CeAM/3CeAM/blob/master/rewrite/npc/3ceam/3ceam_stylist.txt

using latest rev idathena
using latest supported client idathena

**Comment by ernestfegarido** [comment]
do we have this script function? :( @nanakiwurtz @exneval @cydh @jetkappu

**Comment by exneval** [comment]
because opendressroom(0) should be opendressroom(1)
